#!/bin/bash

echo
echo
echo
echo "================================================================================"
echo "="
echo "=    Process:    $1"
echo "=    Command:    $2"
echo "=    Run at:     "$(date "+%Y-%m-%d %H:%M:%S")
echo "=    Run by:     "`whoami`
echo "="
echo "================================================================================"
echo
echo
