#!/bin/bash

curl -sL https://raw.githubusercontent.com/simonziegler/w10-linux-azure-setup/master/create-log-directory > /tmp/create-log-directory
curl -sL https://raw.githubusercontent.com/simonziegler/w10-linux-azure-setup/master/log-banner > /tmp/log-banner
chmod 775 /tmp/create-log-directory
chmod 775 /tmp/log-banner

DEVENV=$1

LOGS=$(/tmp/create-log-directory "setup-w10-linux-environment")

read -p "Enter your name (first last): " USERNAME
read -p "Enter your email address:     " EMAIL


#########################################
#
# Install curl, man, vim and git
#
#########################################

CURRLOG=$LOGS/01-install-vim-git

COMMAND="sudo apt-get update"
/tmp/log-banner "01a Update APT" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="sudo apt-get install curl man vim git"
/tmp/log-banner "01b Install vim and git" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="sudo apt-get install software-properties-common"
/tmp/log-banner "01c Install APT Software Properties" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

echo "colo blue" > ~/.vimrc
git config --global user.name "$USERNAME"
git config --global user.email "$EMAIL"
git config --global core.editor "vim"


#########################################
#
# Install Python & libffi
#
#########################################

CURRLOG=$LOGS/02-install-python-libffi

COMMAND="sudo add-apt-repository ppa:jonathonf/python-3.7"
/tmp/log-banner "02a Add Python Repository" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="sudo apt-get update"
/tmp/log-banner "02b APT Update" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="sudo apt-get install python3.7"
/tmp/log-banner "02c Install Python 3.7" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="sudo apt-get install python3.7-dev"
/tmp/log-banner "02d Install Python 3.7 Dev" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="sudo apt-get install -y libffi-dev"
/tmp/log-banner "02e Install Libffi Dev" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1


#########################################
#
# Install the Azure CLI
#
#########################################

CURRLOG=$LOGS/03-install-azure-cli

COMMAND="curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"
/tmp/log-banner "03a Install the Azure CLI" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="az extension add --name azure-devops"
/tmp/log-banner "03b Install the Azure Devops CLI" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1


#########################################
#
# Install kubectl and helm
#
#########################################

CURRLOG=$LOGS/04-install-kubectl

COMMAND="sudo apt-get update && sudo apt-get install -y apt-transport-https"
/tmp/log-banner "04a Install APT Transport HTTPS" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
/tmp/log-banner "04b Add Google keys to APT" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="echo \"deb https://apt.kubernetes.io/ kubernetes-xenial main\" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list"
/tmp/log-banner "04c Some kubectl Stuff" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="sudo apt-get update"
/tmp/log-banner "04d APT Update" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="sudo apt-get install -y kubectl"
/tmp/log-banner "04e Install kubectl" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1

COMMAND="curl -L https://git.io/get_helm.sh | sudo bash"
/tmp/log-banner "04f Install helm" "$COMMAND" |& tee -a $CURRLOG 2>&1
eval $COMMAND |& tee -a $CURRLOG 2>&1
